<a href="https://colab.research.google.com/github/fahmi54321/ml_multiple_linear_regression_1/blob/main/evaluasi_multiple_linear_regression_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv')

# iloc[row,column]
#  : = semua data,
#  :-1 = semua data, kecuali data terakhir,
#  -1 = data terakhir,

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [5]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

## Predicting the Training set results

In [6]:
y_pred_train = regressor.predict(x_train)
# set_printoptions => Set printing options
# precision => berapa angka dibelakang koma
np.set_printoptions(precision= 2)

# concatenate => menggabungkan array dalam satu baris
# concatenate ((a1, a2, ..), axis)
# concatenate axis => 0 = wanna do a vertical concatenation
#                     1 = wanna do a horizontal concatenation

y_pred_train_reshape = y_pred_train.reshape(len(y_pred_train),1) # convert dari tampilan horizontal ke vertikal
y_train_reshape = y_train.reshape(len(y_train),1) # convert dari tampilan horizontal ke vertikal
print(np.concatenate((y_pred_train_reshape,y_train_reshape), 1))

[[472.69 473.93]
 [466.   467.87]
 [427.19 431.97]
 ...
 [463.72 459.01]
 [469.54 462.72]
 [431.28 428.12]]


## Predicting the Test set results

In [7]:
y_pred_test = regressor.predict(x_test)
# set_printoptions => Set printing options
# precision => berapa angka dibelakang koma
np.set_printoptions(precision= 2)

# concatenate => menggabungkan array dalam satu baris
# concatenate ((a1, a2, ..), axis)
# concatenate axis => 0 = wanna do a vertical concatenation
#                     1 = wanna do a horizontal concatenation

y_pred_test_reshape = y_pred_test.reshape(len(y_pred_test),1) # convert dari tampilan horizontal ke vertikal
y_test_reshape = y_test.reshape(len(y_test),1) # convert dari tampilan horizontal ke vertikal
print(np.concatenate((y_pred_test_reshape,y_test_reshape), 1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


## Evaluating the Model Train set Performance

In [10]:
from sklearn.metrics import r2_score
r2_score(y_train, y_pred_train)

0.9277253998587902

## Evaluating the Model Test set Performance

In [11]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_test)

0.9325315554761303